### ISSUE TITLE
`arc inlines` is no more

### ISSUE THREAD

**Issue by Tarrasch** [jlfwong/vim-arcanist#1]
Which kind of renders this vim plugin not so useful. I tried googling for what happened to `arc inlines`, but it seems like I'm the only one on the internet who cares. :-/

**Comment by jlfwong** [comment]
Yeah :(

I just updated the README to indicate that fact. It was a pretty handy feature while it was around.

**Comment by Tarrasch** [comment]
Hmm, you don't happen to have any insights on top of your head why it was removed?

**Comment by jlfwong** [comment]
https://secure.phabricator.com/D9464 might have some context?
